spring:
    datasource:
      url: jdbc:mysql://192.168.223.130:3306/shadowsocks?useUnicode=true&characterEncoding=utf8
      username: root
      password: StevenMichael88
      type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 8822
  contextPath: /shadowsocks

global:
  url: "http://localhost:8822"
  webUrl: "http://localhost"