spring:
    datasource:
      url: jdbc:mysql://localhost:3306/shadowsocks?useUnicode=true&characterEncoding=utf8
      username: root
      password: StevenMichael88

server:
  port: 8822
  contextPath: /shadowsocks

global:
  domain: "localhost"